services:
  data_generator:
    build:
        dockerfile: ./container/datagenerator/Dockerfile
    entrypoint: 
      - python
      - ./opc_data_generator.py
    container_name: opc_data_generator
    restart: on-failure
    # expose:
    #   - "4840"
    ports:
      - "4840:4840"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
    - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    container_name: kafka
    hostname: kafka
    ports:
    - "9092:9092"
    # expose:
    # - "9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
    - zookeeper

  opc_producer:
    build:
        dockerfile: ./container/opc/Dockerfile
    entrypoint: 
      - python
      - ./opc_producer.py
    container_name: opc_producer
    restart: always
    depends_on:
      - kafka

  opc_consumer:
    build:
        dockerfile: ./container/opc_consumer/Dockerfile
    container_name: opc_consumer
    restart: always
    depends_on:
      - kafka

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  superset:
    image: apache/superset
    container_name: superset
    environment:
      - SUPERSET_LOAD_EXAMPLES=yes
      - SQLALCHEMY_DATABASE_URI=mongodb://root:example@mongo:27017/
      - SQLALCHEMY_ENABLE_POOL_PRE_PING=true
      - PYTHONPATH=/app/superset_config.py
      - SUPERSET_SECRET_KEY=openssl rand -base64 42

    ports:
      - 8088:8088
    # volumes:
    #   - ./superset:/app/superset
    depends_on:
      - mongo
    command: "superset run -p 8088 -h 0.0.0.0"

#   db:
#     image: postgres
#     container_name: local_pgdb
#     restart: always
#     ports:
#       - "54320:5432"
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: admin
#     volumes:
#       - local_pgdata:/var/lib/postgresql/data

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin4_container
#     restart: always
#     ports:
#       - "5050:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@test.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin
# volumes:
#   local_pgdata:
#   pgadmin-data:

networks:
  mockup_network:
    driver: host
    name: mockup_network